export const _ERROR_IN_REDUCER = "ERROR_IN_REDUCER";
export const _DELETE_RESULT = "DELETE_RESULT";

export const _INIT_LOCAL_STATE = "INIT_LOCAL_STATE";
export const _SAVE_LOCAL_STATE = "SAVE_LOCAL_STATE";

export const _TOGGLE_DARK = "TOGGLE_DARK";
export const _TOGGLE_LEFT_SIDERBAR_MOBILE = "TOGGLE_LEFT_SIDERBAR_MOBILE";
export const _TOGGLE_LEFT_SIDERBAR = "TOGGLE_LEFT_SIDERBAR";
export const _MINIMIZE_LEFT_SIDERBAR = "MINIMIZE_LEFT_SIDERBAR";
export const _CLOSE_LEFT_SIDERBAR = "CLOSE_LEFT_SIDERBAR";

export const _TOGGLE_RIGHT_SIDERBAR = "TOGGLE_RIGHT_SIDERBAR";

export const _LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const _LOGIN_FAILED = "LOGIN_FAILED";

export const _TOKEN_CHECK_SUCCESS = "TOKEN_CHECK_SUCCESS";
export const _TOKEN_CHECK_FAILED = "TOKEN_CHECK_FAILED";

export const _LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const _LOGOUT_FAILED = "LOGOUT_FAILED";

export const _RESET_ACTIVE_USER = "RESET_ACTIVE_USER";
